config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:show, :new, :create] do
    member do
      get :like_posts
    end
  end
  
  resources :posts, only: [:show, :new, :create, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end
  
  resources :likes, only: [:create, :destroy]
  
  get 'rankings/like', to: 'rankings#like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, presence: true, length: { maximum: 5000 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, presence: true
  validates :post_id, presence: true
  
  def self.ranking
    self.group(:post_id).order('count_post_id DESC').limit(10).count(:post_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  # 1:多のアソシエーション
  has_many :comments
  
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  # 1:多のアソシエーション
  has_many :posts # User:Post = 1:多
  has_many :comments # User:Comment = 1:多
  
  # Like機能のアソシエーション 
  has_many :likes
  has_many :like_posts, through: :likes, source: :post # User:like = 多:多 の中間モデル設置
  
  def like(post)
    self.likes.find_or_create_by(post_id: post.id)
  end
  
  def unlike(post)
    like = self.likes.find_by(post_id: post.id)
    like.destroy if like
  end
  
  def like_post?(post)
    self.like_posts.include?(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_posts = user.posts.count
    @count_likes = user.likes.count
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def show
    @comments = @post.comments.order('created_at ASC').page(params[:page])
  end
  
  def new
    @comment = Comment.new
  end
  
  def create
    post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post = Post.find(params[:post_id])
    
    if @comment.save
      flash[:success] = '送信完了！'
      redirect_to root_url
    else
      @post = Post.find(params[:post_id])
      @comment = Comment.new
      @comments = @post.comments.order('created_at ASC').page(params[:page])
      
      # @comment = current_user.comments.order('created_at ASC').page(params[:page])
      flash.now[:danger] = '送信失敗！'
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = '削除完了！'
    redirect_to root_url
  end
  
  
  private

  def comment_params
    params.require(:comment).permit(:content)
  end
  
  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    unless @comment
      redirect_to root_url
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    post = Post.find(params[:post_id])
    current_user.like(post)
    flash[:success] = "質問をLikeしました！"
    redirect_to root_url
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.unlike(post)
    flash[:danger] = "質問のLikeを解除しました！"
    redirect_to root_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.order('created_at ASC').page(params[:page])
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      flash[:success] = '送信完了！'
      redirect_to root_url
    else
      @posts = current_user.posts.order('created_at DESC').page(params[:page])
      flash.now[:danger] = '送信失敗！'
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    Like.where(post_id: @post.id).delete_all
    @post.destroy
    flash[:success] = '削除完了！'
    redirect_to root_url
  end
  
  
  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def like
    @ranking_counts = Like.ranking
    @posts = Post.find(@ranking_counts.keys)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = 'ログイン完了！'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログイン失敗！'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @post = current_user.posts.build  # form_for 用
      @posts = Post.all.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :likes]
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = '登録完了！'
      redirect_to @user
    else
      flash.now[:danger] = '登録失敗！'
      render :new
    end
  end
  
  def like_posts
    @user = User.find(params[:id])
    @like_posts = current_user.like_posts.page(params[:page])
    counts(@user)
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rainkings_helper.rb
module RainkingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/comments/_comments.html.erb
<ul class="media-list">
  <% @post.comments.each do |comment| %>
    <% user = comment.user %>
    <li class="media">
      <img class="mr-3 rounded" src="<%= gravatar_url(user, options = { size: 70 }) %>" alt="">
      <div class="media-body">
        <div>
         <%= link_to user.name, user_path(user), class: 'badge badge-secondary' %> <span class="text-muted">さんのコメント <%= comment.created_at %> </span>
        </div>
        <div>
          <p><%= comment.content %></p>
        </div>
        <div>
          <% if current_user == comment.user %>
            <%= link_to "削除", post_comment_path(@post, comment), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-outline-danger btn-sm' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate comments %>
</ul>

app/views/comments/_new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_for([post, comment]) do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: 'form-control', placeholder: 'コメントしたいこと（500字以内）', rows: 7 %>
      </div>
      <%= f.submit '送信', class: 'btn btn-outline-dark btn-block' %>
    <% end %>
  </div>
</div>

app/views/likes/_like_button.html.erb
<% if current_user.like_post?(@post) %>
  <%= form_for(current_user.likes.find_by(post_id: @post.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :post_id, @post.id %>
    <%= f.submit 'Unike', class: "btn btn-outline-danger btn-sm" %>
  <% end %>
<% else %>
  <%= form_for(current_user.likes.build) do |f| %>
    <%= hidden_field_tag :post_id, @post.id %>
    <%= f.submit 'Like!', class: "btn btn-outline-danger btn-sm" %>
  <% end %>
<% end %>

app/views/posts/_posts.html.erb
<ul class="title media-list">
  <% posts.each do |post| %>
    <% user = post.user %>
    <li class="media">
      <img class="mr-3 rounded" src="<%= gravatar_url(user, options = { size: 70 }) %>" alt="">
      <div class="media-body">
        <div>
         <%= link_to user.name, user_path(user), class: 'badge badge-secondary' %> <span class="text-muted">さんの質問 <%= post.created_at %> </span>
        </div>
        <div>
          <p><%= link_to post.title, post_path(post), class: 'btn btn-outline-link' %></p>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate posts %>
</ul>

app/views/posts/new.html.erb
<div class="title">
  <h1 class="text-center">質問してみる？</h1>
</div>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_for(@post) do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class: 'form-control', placeholder: 'タイトル（20字以内）' %>
      </div>
        
      <div class="form-group">
        <%= f.text_area :content, class: 'form-control', placeholder: '質問したいこと（500字以内）', rows: 7 %>
      </div>
      <%= f.submit '送信', class: 'btn btn-outline-dark btn-block' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="title">
  <h1 class="text-center">質問</h1>
</div>
  <div class="media col-md-6 offset-md-3">
    <img class="mr-3 rounded" src="<%= gravatar_url(@post.user, options = { size: 70 }) %>" alt="">
    <div class="media-body">
      <div>
        <%= link_to @post.user.name, user_path(@post.user), class: 'badge badge-secondary' %><span class="text-muted">さんの質問 <%= @post.created_at %> </span>
      </div>
      <div>
        <p><%= @post.title %> </p>
      </div>
      <div>
        <p><%= @post.content %></p>
      </div>
      <ul class="list-inline">
        <li class="list-inline-item"><%= render 'likes/like_button', user: @user %></li>
        <li class="list-inline-item">
          <% if current_user == @post.user %>
            <%= link_to "削除", @post, method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-outline-danger btn-sm' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<div>
  <%= render 'comments/new', post: @post, comment: @comment %>
</div>
<div class="row title">
  <div class="media col-md-6 offset-md-3">
    <%= render 'comments/comments', comments: @comments %>
  </div>
</div>

app/views/rankings/like.html.erb
<h1 class="title text-center">ランキング</h1>
<% if @posts.present? %>
  <div class="title row">
    <div class="col-md-6 offset-md-3">
      <ul class="media-list list-unstyled">
        <% @posts.each_with_index do |post, index| %>
          <li class="text-center">
            <h4><%= index+1 %>位: <span class="badge badge-info"><%= @ranking_counts[post.id] %> Likes</span></h1>
          </li>
          <li class="media">
            <img class="mr-3 rounded" src="<%= gravatar_url(post.user, options = { size: 70 }) %>" alt="">
            <div class="media-body">
              <div>
                <%= link_to post.user.name, user_path(post.user), class: 'badge badge-secondary' %> <span class="text-muted">さんの質問 <%= post.created_at %> </span>
              </div>
              <div>
                <p><%= link_to post.title, post_path(post), class: 'btn btn-outline-link' %></p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="col-md-6 offset-md-3">
    <%= render 'posts/posts', posts: @posts %>
  </div>
<% else %>
  <% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>北欧のこと</h1>
        <h1>聞こう。答えよう。</h1>
          <%= link_to '登録する', signup_path, class: 'btn btn-light btn-lg' %>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/users/like_posts.html.erb
<div class="title user-profile">
  <div class="icon text-center">
    <img class="rounded" src="<%= gravatar_url(@user, size: 100) %>" alt="">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  <ul class="nav nav-tabs justify-content-center">
    <li class="<%= "nav-item" if current_page?(user_path(@user)) %>"><%= link_to user_path(@user), class: 'nav-link' do %> <%= @user.name %>さんの質問 <span class="badge"><%= @count_posts %></span><% end %></li>
    <li class="<%= "nav-item" if current_page?(like_posts_user_path(@user)) %>"><%= link_to like_posts_user_path(@user), class: 'nav-link active' do %> Like <span class="badge"><%= @count_posts %></span><% end %></li>
  </ul>
  <div class="row">
    <div class="media col-md-6 offset-md-3">
      <%= render 'posts/posts', posts: @like_posts %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="title">
  <h1 class="text-center">新規登録</h1>
</div>

<div class="row"> 
  <div class="col-md-6 offset-md-3">
    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.submit '登録する', class: 'btn btn-outline-dark btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="title user-profile">
  <div class="icon text-center">
    <img class="rounded" src="<%= gravatar_url(@user, size: 100) %>" alt="">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
    <ul class="nav nav-tabs justify-content-center">
      <li class="<%= "nav-item" if current_page?(user_path(@user)) %>"><%= link_to (@user), class: 'nav-link active' do %> <%= @user.name %>さんの質問 <span class="badge"><%= @count_posts %></span><% end %></li>
      <li class="<%= "nav-item" if current_page?(like_posts_user_path(@user)) %>"><%= link_to like_posts_user_path(@user), class: 'nav-link' do %> Like <span class="badge"><%= @count_posts %></span><% end %></li>
    </ul>
    <div class="row">
      <div class="media col-md-6 offset-md-3">
        <%= render 'posts/posts', posts: @posts %>
      </div>
    </div>
  </div>
</div>